# Generated by Django 5.1.7 on 2025-06-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='quiz',
            name='correct_option',
            field=models.CharField(default='A', max_length=10),
        ),
    ]
