# Generated by Django 5.1.7 on 2025-06-27 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0002_remove_quiz_correct_answer_quiz_correct_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='correct_option',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='topic',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorapp.quiz'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorapp.question'),
        ),
    ]
