# Generated by Django 5.2.3 on 2025-06-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0004_quiz_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='correct_answer',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='correct_option',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
