# Generated by Django 5.2.3 on 2025-06-29 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0005_remove_quiz_correct_answer_alter_quiz_correct_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='question',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
